### ISSUE TITLE
no such attribute _blink_thread

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#503]
I'm repeatedly hitting this issue when `close()` is called on devices:

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gpiozero/devices.py", line 162, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/gpiozero/boards.py", line 299, in close
    self._stop_blink()
  File "/usr/local/lib/python3.5/dist-packages/gpiozero/boards.py", line 375, in _stop_blink
    if self._blink_thread:
  File "/usr/local/lib/python3.5/dist-packages/gpiozero/boards.py", line 711, in __getattr__
    return super(TrafficLights, self).__getattr__(name)
  File "/usr/local/lib/python3.5/dist-packages/gpiozero/devices.py", line 307, in __getattr__
    raise AttributeError("no such attribute %s" % name)
AttributeError: no such attribute _blink_thread
```

One way to reproduce it is:

```python
from gpiozero import *
import pytest

with pytest.raises(ValueError):
    TrafficLights()
```

**Comment by lurch** [comment]
Does #494 fix that? :-)
If not I'll add this to my list of things to look at over the weekend.

**Comment by bennuttall** [comment]
It doesn't seem to! :(

**Comment by lurch** [comment]
Feel free to give #507 a test ;-)
