### ISSUE TITLE
backtrace on script (service) stop

### ISSUE THREAD

**Issue by asavah** [RPi-Distro/python-gpiozero#649]
```
May 26 16:45:30 rpi3 systemd[1]: Stopping keypad handler...
May 26 16:45:30 rpi3 keypad.py[550]: signal 15
May 26 16:45:31 rpi3 keypad.py[550]: Error in atexit._run_exitfuncs:
May 26 16:45:31 rpi3 keypad.py[550]: Traceback (most recent call last):
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
May 26 16:45:31 rpi3 keypad.py[550]:     func(*targs, **kargs)
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 483, in _shutdown
May 26 16:45:31 rpi3 keypad.py[550]:     _devices_shutdown()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 476, in _devices_shutdown
May 26 16:45:31 rpi3 keypad.py[550]:     dev.close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/output_devices.py", line 155, in close
May 26 16:45:31 rpi3 keypad.py[550]:     super(DigitalOutputDevice, self).close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/mixins.py", line 77, in close
May 26 16:45:31 rpi3 keypad.py[550]:     super(SourceMixin, self).close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 394, in close
May 26 16:45:31 rpi3 keypad.py[550]:     self._pin.close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/pins/rpigpio.py", line 107, in close
May 26 16:45:31 rpi3 keypad.py[550]:     GPIO.cleanup(self.number)
May 26 16:45:31 rpi3 keypad.py[550]: RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
May 26 16:45:31 rpi3 keypad.py[550]: Error in sys.exitfunc:
May 26 16:45:31 rpi3 keypad.py[550]: Traceback (most recent call last):
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
May 26 16:45:31 rpi3 keypad.py[550]:     func(*targs, **kargs)
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 483, in _shutdown
May 26 16:45:31 rpi3 keypad.py[550]:     _devices_shutdown()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 476, in _devices_shutdown
May 26 16:45:31 rpi3 keypad.py[550]:     dev.close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/output_devices.py", line 155, in close
May 26 16:45:31 rpi3 keypad.py[550]:     super(DigitalOutputDevice, self).close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/mixins.py", line 77, in close
May 26 16:45:31 rpi3 keypad.py[550]:     super(SourceMixin, self).close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/devices.py", line 394, in close
May 26 16:45:31 rpi3 keypad.py[550]:     self._pin.close()
May 26 16:45:31 rpi3 keypad.py[550]:   File "/usr/lib/python2.7/site-packages/gpiozero-1.4.1-py2.7.egg/gpiozero/pins/rpigpio.py", line 107, in close
May 26 16:45:31 rpi3 keypad.py[550]:     GPIO.cleanup(self.number)
May 26 16:45:31 rpi3 keypad.py[550]: RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
May 26 16:45:31 rpi3 systemd[1]: Stopped keypad handler.
```

Inserting
```
        GPIO.setmode(GPIO.BCM)
```
above the following line https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/pins/rpigpio.py#L106 prevents backtrace on stop for me.

There is a reproducer https://github.com/RPi-Distro/python-gpiozero/issues/605

**Comment by asavah** [comment]
@bennuttall May i ask why this issue was closed without an explanation or a fix?
